### Arrays
Printing the array in reverse order

In [1]:
import numpy

def arrays(arr):
    arra=numpy.array(arr,float)
    arra=arra[::-1]
    return arra
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

5 7 9 1 3
[3. 1. 9. 7. 5.]


### Reshaping The Array
Taking 9 space separated integer inputs and converting it into a 3X3 Matrix.

In [19]:
import numpy

a=list(map(int, input().split()))
b=numpy.array(a,int)
#print(b)

# FIRST WAY
# USING:       numpy.reshape(array_name,(required,shape))

#print(numpy.reshape(b,(3,3)))     # 

# Another way of changing the shape
# using:      array_name.shape=(requred,shape)

b.shape=(3,3)
print(b)

1 2 3 6 5 4 7 8 9
[1 2 3 6 5 4 7 8 9]
[[1 2 3]
 [6 5 4]
 [7 8 9]]


### Transpose and Flattened(Medium level)


$ TASKS $
- 1. Taking Rows(n) and columns(m) input
- 2. then taking the elements input in 'n' rows each 'm' column wide.
- 3. Transposing the matrix
- 4. Flattened the matrix  

In [2]:
import numpy
n,m=map(int,input().split())
#print(n)
#print(m)
h=[]
for i in range(n):
    r=list(map(int,input().split()))
    h.append(r)

#print(h)
l=numpy.array(h,int)
#print(l)
#print(l.shape)   # nxm shape

# First getting a transpose.
print(numpy.transpose(l))
# or we can use 
# l.shape=(m,n)

# Flattened(converts multidimensional matrix into one-d)
print(l.flatten())



2 2
1 2
4 5
[[1 4]
 [2 5]]
[1 2 4 5]
